config/routes.rb
Rails.application.routes.draw do
	
  root 'home#index'
  get '/locations/:id', to: 'locations#show'
  get '/search/:weather', to: 'locations#search', as: "search"

end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :locale
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  def locale
    [city, state].compact.join(', ')
  end

  def coords_nil?
    self.latitude.blank? || self.longitude.blank?
  end

  before_save :geocode, :if => :coords_nil?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @loc = request.location
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :set_location, only: [:show, :edit, :update, :destroy]

	# GET /locations
	# GET /locations.json
	def index
		if params[:search].present?
			@locations = Location.near(params[:search], 10, :order => distance)
		else
			@locations = Location.all
		end
	end

    # results page
	def search
        #wrap in if statement to fall back on asking for coords?
        @coords = Geocoder.coordinates(params[:ip])

        @lat = @coords[0] 
        @lon = @coords[1]

		@destinations = Location.all.where("current_forecast like ?", params[:weather]).sort_by{ |d|
			d.distance_to([@lat, @lon.to_f])
		}.first

		@conditions = ""

        # template helper
		if @destinations
			if params[:weather] == "rain"
				@conditions = "raining"
			elsif params[:weather] == "snow"
				@conditions = "snowing"
			elsif params[:weather] == "clear%"
				@conditions = "sunny"
			else
				@conditions = "different"
			end
		else
			flash[:alert] = "There doesn't appear to be any " + params[:weather].to_s + " anywhere in the U.S. today."
			redirect_to controller: :home, action: :index
		end
	end

	# GET /locations/1
	# GET /locations/1.json
	def show
	end

	# GET /locations/new
	def new
		@location = Location.new
	end

	# GET /locations/1/edit
	def edit
	end

	# POST /locations
	# POST /locations.json
	def create
		@location = Location.new(location_params)

		respond_to do |format|
			if @location.save
				format.html { redirect_to @location, notice: 'Location was successfully created.' }
				format.json { render :show, status: :created, location: @location }
			else
				format.html { render :new }
				format.json { render json: @location.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /locations/1
	# PATCH/PUT /locations/1.json
	#  def update
	#    respond_to do |format|
	#      if @location.update(location_params)
	#        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
	#        format.json { render :show, status: :ok, location: @location }
	#      else
	#        format.html { render :edit }
	#        format.json { render json: @location.errors, status: :unprocessable_entity }
	#      end
	#    end
	#  end

	# DELETE /locations/1
	# DELETE /locations/1.json
	def destroy
		@location.destroy
		respond_to do |format|
			format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_location
		@location = Location.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def location_params
		params.require(:location).permit(:city, :state, :latitude, :longitude)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/home/index.html.erb
<script>
    function getByLatLon() {
		setTimeout(function() {
			navigator.geolocation.getCurrentPosition(GetLocation);
			function GetLocation(location) {
				lat = location.coords.latitude;
				lon = location.coords.longitude;
				$('#latitude').val(lat);
				$('#longitude').val(lon);

				$('.wlink').each( function() {
					var href = $(this).attr('href');
					$(this).attr('href', href + "?latitude=" + lat + '&longitude=' + lon);
				});
				$('#floatingCirclesG').toggle();
				$('.prog-wrapper').toggle();
			}
        } , 10);
    }

    function getByIp() {
        $('.wlink').each( function() {
            var href = $(this).attr('href');
            $(this).attr('href', href + "?ip=" + "<%=  @loc.ip %>");
        });
        $('#floatingCirclesG').toggle();
        $('.prog-wrapper').toggle();
    }

    $(document).ready( function() {
        getByIp();
	});
</script>
<div class="site-wrapper">
	<div class="container">
<!--			<div class="prog-wrapper">
				<h1>Identifying your location...</h1>
				<div id="floatingCirclesG">
					<div class="f_circleG" id="frotateG_01">
					</div>
					<div class="f_circleG" id="frotateG_02">
					</div>
					<div class="f_circleG" id="frotateG_03">
					</div>
					<div class="f_circleG" id="frotateG_04">
					</div>
					<div class="f_circleG" id="frotateG_05">
					</div>
					<div class="f_circleG" id="frotateG_06">
					</div>
					<div class="f_circleG" id="frotateG_07">
					</div>
					<div class="f_circleG" id="frotateG_08">
					</div>
				</div>
		</div>
        -->	
        <div class="row">
			<div class="col-md-12">
				<h1 style="font-size: 84px">Find me the nearest place where weather is:</h1>
				<% flash.each do |message_type, message| %>
					<div class="alert alert-info"><%= message %></div>
				<% end %>
			</div>
		</div>
		<div class="row" style="margin-top: 40px">
			<div class="col-md-12">
				<%= link_to "raining", search_path("rain"), class: "wlink btn btn-primary btn-lg" %>
				<%= link_to "sunny", search_path("clear%"), class: "wlink btn btn-warning btn-lg" %>
				<%= link_to "snowing", search_path("snow"), class: "wlink btn btn-default btn-lg" %>
			</div>
		</div>
		<div class="row" style="margin-top: 40px">
            <div class="col-md-12" style="margin-top: 60px; font-size: 12px;">
                <p>Better Weather uses your location to find the nearest places where the weather is raining, snowing, or sunny, so that you can plan a little getaway from the sunshine or endless snowy days.</p>
            </div>
        </div>
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]--><!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]--><!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]--><!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
				<!--[if (gt IE 9)|!(IE)]><!--> 
				<html lang="en" class="no-js"> 
					<!--<![endif]-->
					<html>
                        <head>
                            <meta name="msvalidate.01" content="82ADE4446168C80ED00BD334BBE07A3D" />
							<meta charset="utf-8">
							<!-- :[ Force latest IE rendering engine ]: -->
							<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
							<meta name="description" content="Find the nearest place it is raining, snowing, or sunny. Location-based better weather forecast near you.">
                            <meta name="author" content="">
                            <meta name="keywords" content="Weather better rain snow sun clouds vacation getaway destination forecast locale near me find weather different weather">
							<!-- :[ Optimize mobile viewpost - link: http://j.mp/bplateviewport ]: -->
							<meta name="viewport" content="width=device-width, initial-scale=1.0">

							<!-- :[ Browser will always ask for them ]: -->
							<link rel="shortcut icon" href="/favicon.ico">
							<link rel="apple-touch-icon" href="apple-touch-icon.png">

							<title>BetterWeather</title>
							<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
							<style>
								#floatingCirclesG{
									width:128px;
									height:128px;
									margin: 48px auto;
									-moz-transform:scale(0.6);
									-webkit-transform:scale(0.6);
									-ms-transform:scale(0.6);
									-o-transform:scale(0.6);
									transform:scale(0.6);
								}

								.f_circleG{
									position:absolute;
									background-color:#000000;
									height:23px;
									width:23px;
									-moz-border-radius:12px;
									-moz-animation-name:f_fadeG;
									-moz-animation-duration:1.04s;
									-moz-animation-iteration-count:infinite;
									-moz-animation-direction:normal;
									-webkit-border-radius:12px;
									-webkit-animation-name:f_fadeG;
									-webkit-animation-duration:1.04s;
									-webkit-animation-iteration-count:infinite;
									-webkit-animation-direction:normal;
									-ms-border-radius:12px;
									-ms-animation-name:f_fadeG;
									-ms-animation-duration:1.04s;
									-ms-animation-iteration-count:infinite;
									-ms-animation-direction:normal;
									-o-border-radius:12px;
									-o-animation-name:f_fadeG;
									-o-animation-duration:1.04s;
									-o-animation-iteration-count:infinite;
									-o-animation-direction:normal;
									border-radius:12px;
									animation-name:f_fadeG;
									animation-duration:1.04s;
									animation-iteration-count:infinite;
									animation-direction:normal;
								}

								#frotateG_01{
									left:0;
									top:52px;
									-moz-animation-delay:0.39s;
									-webkit-animation-delay:0.39s;
									-ms-animation-delay:0.39s;
									-o-animation-delay:0.39s;
									animation-delay:0.39s;
								}

								#frotateG_02{
									left:15px;
									top:15px;
									-moz-animation-delay:0.52s;
									-webkit-animation-delay:0.52s;
									-ms-animation-delay:0.52s;
									-o-animation-delay:0.52s;
									animation-delay:0.52s;
								}

								#frotateG_03{
									left:52px;
									top:0;
									-moz-animation-delay:0.65s;
									-webkit-animation-delay:0.65s;
									-ms-animation-delay:0.65s;
									-o-animation-delay:0.65s;
									animation-delay:0.65s;
								}

								#frotateG_04{
									right:15px;
									top:15px;
									-moz-animation-delay:0.78s;
									-webkit-animation-delay:0.78s;
									-ms-animation-delay:0.78s;
									-o-animation-delay:0.78s;
									animation-delay:0.78s;
								}
								#frotateG_05{
									right:0;
									top:52px;
									-moz-animation-delay:0.91s;
									-webkit-animation-delay:0.91s;
									-ms-animation-delay:0.91s;
									-o-animation-delay:0.91s;
									animation-delay:0.91s;
								}

								#frotateG_06{
									right:15px;
									bottom:15px;
									-moz-animation-delay:1.04s;
									-webkit-animation-delay:1.04s;
									-ms-animation-delay:1.04s;
									-o-animation-delay:1.04s;
									animation-delay:1.04s;
								}

								#frotateG_07{
									left:52px;
									bottom:0;
									-moz-animation-delay:1.17s;
									-webkit-animation-delay:1.17s;
									-ms-animation-delay:1.17s;
									-o-animation-delay:1.17s;
									animation-delay:1.17s;
								}

								#frotateG_08{
									left:15px;
									bottom:15px;
									-moz-animation-delay:1.3s;
									-webkit-animation-delay:1.3s;
									-ms-animation-delay:1.3s;
									-o-animation-delay:1.3s;
									animation-delay:1.3s;
								}

								@-moz-keyframes f_fadeG{
									0%{
										background-color:#FFFFFF}

									100%{
										background-color:#000000}

								}

								@-webkit-keyframes f_fadeG{
									0%{
										background-color:#FFFFFF}

									100%{
										background-color:#000000}

								}

								@-ms-keyframes f_fadeG{
									0%{
										background-color:#FFFFFF}

									100%{
										background-color:#000000}

								}

								@-o-keyframes f_fadeG{
									0%{
										background-color:#FFFFFF}

									100%{
										background-color:#000000}

								}

								@keyframes f_fadeG{
									0%{
										background-color:#FFFFFF}

									100%{
										background-color:#000000}

								}
								.prog-wrapper {
									height: 100%;
									width: 100%;
									background-color: rgba(0,0,0,0.8);
									position: fixed;
									top: 0;
									left: 0;
									z-index: 100;
								}
								.prog-wrapper h1 {
									width: 320px;
									margin: 24px auto;
								}
							</style>
							<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
							<%= csrf_meta_tags %>
							<script>
								(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
										(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
									m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
								})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

								ga('create', 'UA-63380702-1', 'auto');
								ga('send', 'pageview');

							</script>
						</head>
						<body>

							<%= yield %>

						</body>
					</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag locations_path, :method => :get do %>
	<p>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search Near", :name => nil %>
	</p>
<% end %>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.city %></td>
        <td><%= location.state %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/search.html.erb
<% imagePath = @conditions + '.jpg' %>
<div style="height: 100%; background: black url(<%= image_path imagePath %>) no-repeat top center fixed; background-size: cover">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4">
				<p id="notice"><%= notice %></p>
				<h1>The nearest place where it's <%= @conditions %> is:</h1>
			</div>
		</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<table class="table lead">
					<tr>
						<td><%= @destinations.city %></td>
						<td><%= @destinations.state %></td>
					</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<%= link_to "Back", root_url, class: "btn btn-default btn-lg"  %>
		</div>
	</div>
</div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%# link_to 'Edit', edit_location_path(@location) %> |
<%# link_to 'Back', locations_path %>